Add `weight` kwarg to `AlchemiscaleClient.action_tasks` method
openforcefield/alchemiscale pull request #209
Opened 2023-12-04 21:21 UTC by ianmkenney

In this PR, the kwarg `weight` has been added to the `AlchemiScaleClient.action_tasks` method, where its value is added to the data payload. Validation of the weight (restricted to be between 0 and 1, see #208 ) is handled at the API layer. The `Neo4jStore` also now has a `weight` kwarg that defaults to 0.5 (note that the previous weight was 1 and was hard coded).

fixes #202

2023-12-07 13:01 UTC, dotsdl requested changes
Great work @ianmkenney! In reviewing I realized we should pivot our approach from this a bit, using some existing functionality in `Neo4jStore` instead of modifying its `action_tasks` method.

Some additional points/questions:
1. We need an explicit test for `Task` weight setting via the `AlchemiscaleClient` in `tests/integration/interface/client/test_client.py`.
2. Let's change the default `weight` on the `AlchemiscaleClient.action_tasks` method to `None`, and have this mean that no change is made to `weight`s for `Task`s already actioned, and newly-actioned `Task`s retain the default of 0.5.

2023-12-07 13:19 UTC, dotsdl requested changes
A couple small notes.

2023-12-07 13:19 UTC, dotsdl commented on alchemiscale/tests/integration/storage/test_statestore.py
>          # weights should all be the default 1.0
Fix comment.

2023-12-07 13:19 UTC, dotsdl commented on alchemiscale/tests/integration/storage/test_statestore.py
>          # set weights on the tasks to be all 10
Fix comment.

2023-12-07 18:55 UTC, dotsdl commented on alchemiscale/storage/statestore.py
> +                CREATE (th)-[ar:ACTIONS {{weight: {weight}}}]->(task)
Sorry, yes. Make the new default 0.5.

2023-12-12 20:29 UTC, ianmkenney commented on alchemiscale/tests/integration/interface/client/test_client.py
> +            weight = weight * len(task_sks)
Reworked how this is done

2023-12-12 20:29 UTC, ianmkenney commented on alchemiscale/tests/integration/interface/client/test_client.py
> +
Done

2023-12-15 18:55 UTC, dotsdl approved these changes
Great work @ianmkenney! Please merge if satisfied!

2023-12-15 18:55 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +            assert task_weights == _weight
Beautiful!

2023-12-15 18:55 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +    def test_action_tasks_update_weights(
Very nice! Thank you!

2023-12-15 18:55 UTC, dotsdl commented on alchemiscale/tests/integration/interface/client/test_client.py
> +            ([0.25, 0.5, 0.75], False),
Much better!

2023-12-15 21:16 UTC, merged