Network representation optimizations for JSON encoding
openforcefield/alchemiscale pull request #217
Opened 2023-12-22 20:07 UTC by ianmkenney

Fixes #216

This PR implements a graph based optimization for representing gufe objects an order dependent chain of keyed dicts, dramatically reducing memory usage (~ -97% for JSON representation size of our test networks).

2023-12-28 17:55 UTC, dotsdl requested changes
Looking fantastic @ianmkenney! This is a huge improvement!

Can you also add a unit test (not integration test) for each of the methods this PR adds in `alchemiscale.utils`? We want to be sure in a fairly isolated way that any `GufeTokenizable`s these methods handle are working as expected via these unit tests.

2023-12-28 17:55 UTC, dotsdl commented on alchemiscale/tests/integration/interface/test_api.py
> +import networkx as nx
I don't think this import is used in this module.

2023-12-28 18:09 UTC, ianmkenney commented on alchemiscale/interface/client.py
> +import networkx as nx
seems we do, see `get_transformation_tasks`

2023-12-28 19:53 UTC, dotsdl commented on alchemiscale/interface/client.py
> +import networkx as nx
Oh that's strange; not sure how we didn't already have this import :thinking:

2023-12-28 21:24 UTC, ianmkenney commented on alchemiscale/interface/client.py
> +import networkx as nx
we did, I added it as a repeated import because I didn't notice it 😮‍💨

2024-01-04 19:29 UTC, dotsdl approved these changes
Amazing work @ianmkenney! Merging!

2024-01-04 19:30 UTC, merged