Adding bulk task creation server side
openforcefield/alchemiscale pull request #250
Opened 2024-02-27 23:48 UTC by ianmkenney

This PR introduces the `create_tasks` method to the `Neo4jStore`. It attempts to minimize the queries made to the database when creating and extending tasks. From local tests, the performance for $n=1$ task created is the same. When creating thousands of tasks, the runtime drops to about one fifth of its previous value (~23 s to 4 s).

2024-03-05 17:44 UTC, ianmkenney commented
@dotsdl ready for review, just had to expand tests

2024-03-13 21:18 UTC, dotsdl commented
Reviewing now! Thanks @ianmkenney!

2024-03-14 05:46 UTC, dotsdl requested changes
Looking great @ianmkenney! A few things to hit yet to improve it further, but this is already a big improvement.

2024-03-14 05:46 UTC, dotsdl commented on alchemiscale/interface/api.py
> +    transformations: List[str] = Body(embed=True),
Thanks for this one too!

2024-03-14 17:10 UTC, ianmkenney commented on alchemiscale/storage/statestore.py
> +                raise ValueError(f"Cannot extend a `deleted` or `invalid` Task: {node}")
The `__str__` method of py2neo.Node chokes on the neo4j datetime object, without the cast we get `TypeError("Cypher literal values of type %s.%s are not supported")`.

2024-03-15 00:02 UTC, dotsdl commented on alchemiscale/storage/statestore.py
> +                raise ValueError(f"Cannot extend a `deleted` or `invalid` Task: {node}")
Can we just give the `Task` `ScopedKey` in the exception output instead of the whole `Node`?

2024-03-15 18:07 UTC, ianmkenney commented on alchemiscale/storage/statestore.py
> +                if _extends is not None:
Added validation and we now raise a ValueError if we try to extend the wrong Task, see the new test

2024-03-15 22:14 UTC, dotsdl approved these changes
Amazing work @ianmkenney! Feel free to merge if satisfied!

2024-03-19 15:39 UTC, merged