Allow a Task to be actioned it if EXTENDS an incomplete Task
openforcefield/alchemiscale pull request #94
Opened 2023-02-20 23:08 UTC by hmacdope

- modified the `action_tasks` code to allow actioning of tasks via an `EXTENDS` relationship even if not complete 
- Equivalent changes to the `claim` code to only allow claiming of extends tasks if the preceding node is complete.

2023-02-21 00:16 UTC, hmacdope commented
@dotsdl I think this is ready for review. There is just one failing test which Is possibly on the GUFE side and is being triggered as we now have EXTENDS tasks.

2023-02-21 00:31 UTC, hmacdope commented
Specifically GUFE is complaining about the lack of a `protocol_unit_result` method. It may be a GUFE versioning thing, but thought best to discuss.

2023-02-21 10:36 UTC, dotsdl requested changes
@hmacdope looking good, but one major note that needs addressing before we proceed. Should be able to drop consideration of EXTENDS in `action_tasks`.

2023-02-21 21:53 UTC, hmacdope commented on alchemiscale/storage/statestore.py
> +                }}
I don't know why I had in my head that we wanted to `ACTION` any tasks that `EXTEND` the target task. My bad, I'll fix it up ASAP.

2023-02-21 21:53 UTC, hmacdope commented on alchemiscale/storage/statestore.py
> +                            if record is not None:
Yep makes sense.

2023-02-21 21:55 UTC, hmacdope commented on alchemiscale/storage/statestore.py
> +                }}
`COLLECT` makes it available in the outer scope, but the whole thing should simplify when we remove any EXTENDS funky business.

2023-02-21 23:23 UTC, hmacdope commented
Fixed @dotsdl sorry about that.

2023-02-22 21:35 UTC, dotsdl approved these changes
Looks great @hmacdope! Thank you!

Merging!

2023-02-22 21:39 UTC, dotsdl commented
Fixing CI; will get it sorted then merge.

2023-02-22 22:28 UTC, merged